pipeline {
    agent {
        docker {
            image 'maven:3.9.0'
            args '-v /root/.m2:/root/.m2 -p 8080:8080'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
                sh "chmod +x -R ${env.WORKSPACE}"
                sh './jenkins/scripts/test.sh'

            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Manual approval') {
            steps {
                input message: 'Lanjutkan ke tahap Deploy?'
            }
        }
        stage('Deploy') {
            environment {
                RAILWAY_API_TOKEN = credentials('RAILWAYAPI')
                RAILWAY_TOKEN = credentials('RAILWAYPROJECT')
            }
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
