node {
    docker.image('maven:3.9.3').inside('-v /root/.m2:/root/.m2 -p 8080:8080') {
        stage('Build') {
            sh 'mvn -B -e -X -DskipTests clean package'
        }
        
        stage('Test') {
            sh 'mvn test'            
            junit 'target/surefire-reports/*.xml'
        }
        
        stage('Deploy') {
            sh './jenkins/scripts/deliver.sh'
        }
    }
}
